# Generated by Django 4.1.7 on 2023-03-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='create_datetime',
            field=models.DateField(auto_now_add=True, default='2023-03-03'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='update_date',
            field=models.DateField(auto_now=True),
        ),
    ]
