# Generated by Django 4.1.1 on 2023-02-12 17:16

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=100, validators=[django.core.validators.MinLengthValidator(2, '"name" field value less than two symbols')], verbose_name='name')),
                ('description', models.TextField(db_column='description', max_length=500, validators=[django.core.validators.MinLengthValidator(2, '"description" field value less than two symbols')], verbose_name='description')),
                ('start', models.DateField(blank=True, default=datetime.date.today, null=True)),
            ],
            options={
                'db_table': 'groups_table',
            },
        ),
    ]
