# Generated by Django 4.1.7 on 2023-03-02 15:50

import datetime
from django.db import migrations, models
import groups.validators


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_group_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='create_datetime',
            field=models.DateField(auto_now_add=True, default='2023-03-02 17:50:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='update_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='start',
            field=models.DateField(default=datetime.datetime.utcnow, validators=[groups.validators.validate_start_date]),
        ),
    ]
