# Generated by Django 4.1.1 on 2023-02-14 17:45

from django.db import migrations, models
import core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_birthday_alter_student_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, validators=[core.validators.ValidEmailDomain('gmail.com', 'yahoo.com')]),
        ),
    ]
