# Generated by Django 4.1.7 on 2023-03-02 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_group_create_datetime_group_end_group_update_date_and_more'),
        ('students', '0006_student_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='create_datetime',
            field=models.DateField(auto_now_add=True, default='2023-03-02'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='groups.group'),
        ),
        migrations.AddField(
            model_name='student',
            name='update_date',
            field=models.DateField(auto_now=True),
        ),
    ]
